### ISSUE TITLE
doesn't seem to work over localwp

### ISSUE THREAD

**Issue by dospuntocero** [Log1x/poet#14]
when i use this:
 wp acorn vendor:publish --provider="Log1x\Poet\PoetServiceProvider"

this is the result:
PHP Warning:  Use of undefined constant WP_CONTENT_DIR - assumed 'WP_CONTENT_DIR' (this will throw an Error in a future version of PHP) in /mnt/c/Users/fran/Local Sites/hghill/app/public/wp-includes/load.php on
 line 115

Error: Your PHP installation appears to be missing the MySQL extension which is required by WordPress.

**Comment by Log1x** [comment]
Hm – that's a strange error.

Outside of that, passing `--provider` doesn't work currently and needs fixed in Acorn.

Try just running `wp acorn vendor:publish` and choosing Poet from the options instead.

**Comment by Log1x** [comment]
Ah, I missed the `localwp` part of your title. I haven't used that before. Do normal `wp` commands work properly?
