### ISSUE TITLE
MediaCloud Plugin overrides Illuminate collapse() function

### ISSUE THREAD

**Issue by conradfuhrman** [Log1x/poet#15]
Reaching out as I'm not sure how to solve this one. MediaCloud's (https://mediacloud.press/) uses similar Illuminate classes that define the collapse() method and it seems to be overriding Poet's use of collapse() directly from the Illuminate vendor. I've reached out to MediaPress to see if this is something they can resolve, but haven't heard back. I was curious if this is something that is a scoping issue or similar. I've actually never run into this before.

Of course, I'm happy to help resolve, test, etc., but this is a bit out of my comfort zone on where a solution might be. Appreciate your work and really want to give Poet a try!

**Comment by Log1x** [comment]
hmm strange. is it throwing an error?

**Comment by conradfuhrman** [comment]
No explicit error, but when MediaPress is disabled everything works awesome. When it's  enabled I did a var_dump on the collection chained methods and collapse returns an empty array rather than the proper response of the post types. 

The method from MediaPress is slightly different so that's where my assumption lies with their class. 

So technically it's a soft failure. Also this is a brand new Sage 10 project and MediaPress is currently the only plugin other than ACF.

**Comment by Log1x** [comment]
Confirmed the issue. Will try to push a fix tonight.

**Comment by conradfuhrman** [comment]
That's amazing! Looking forward to seeing how you resolved it and thanks a ton for providing a fix.

**Comment by conradfuhrman** [comment]
Going to test tonight the newest version 4.2.5 as it looks like a lot updated from MediaPress. Will let you know if the issue still persists.

**Comment by conradfuhrman** [comment]
Tested with 4.2.5. Still have the same issue unfortunately.

**Comment by Log1x** [comment]
yeah. annoyingly they are autoloading `helpers.php` from their old `Illuminate\Support\Collection` and it's registering before Sage's. I fixed it on https://github.com/Log1x/poet/pull/16/files but it's not stable yet

**Comment by conradfuhrman** [comment]
Gotcha. Anything I can do to help?

**Comment by Log1x** [comment]
If you have time to burn, feel free to try that PR so far. I will have to swing back around to it tonight – I honestly can't remember where I left off. :(

**Comment by conradfuhrman** [comment]
Sounds good, I'll fork it and see what I come up with in the next day or two.
