### ISSUE TITLE
Unable to publish the config/poet.php file

### ISSUE THREAD

**Issue by precisioncoder13** [Log1x/poet#23]
Hello,

I am trying this package in one task with Sage-10 & facing the issue with publishing it by the given command `wp acorn vendor:publish --provider="Log1x\Poet\PoetServiceProvider"`. 

Error: "Unable to locate publishable resources."

Can you please suggest any other way to publish it? or any help to fix it.

Thanks.

**Comment by precisioncoder13** [comment]
Sorry for taking your time.

It's fixed by using `wp acorn vendor:publish` and selecting the package from the given list.

Thanks for the great package.

**Comment by paulbrzeski** [comment]
Can @precisioncoder13's answer please be used to update the README? :)

**Comment by liviuzachin** [comment]
if that is not working, you must run `wp acorn vendor:publish --tag=acorn:init` too

**Comment by erralb** [comment]
Hi, I have a similar question :

```
wp acorn vendor:publish --provider="Log1x\Poet\PoetServiceProvider"
No publishable resources for tag [].
Publishing complete.

wp acorn vendor:publish 
 Which provider or tag's files would you like to publish?:
  [0] Publish files from all providers and tags listed below
  [1] Provider: Roots\Acorn\Providers\AcornServiceProvider
  [2] Tag: acorn
 > 
```

I tried publishing everything, and I also tried `wp acorn vendor:publish --tag=acorn:init` but the poet.php file is not created into the config folder.  Am I missing something ?
