### ISSUE TITLE
Query CPT by Taxonomy

### ISSUE THREAD

**Issue by ASDWcodes** [Log1x/poet#26]
Hello,

Is there any documentation, best practices, or code examples for how to configure Poet so that custom post types can be queried by taxonomies?

My goal is to: 
- Register a CPT (say 'book') 
- Register taxonomies (say 'genre', 'language')
- Query the CPT by a single taxonomy (say 'genre/horror')

I've been digging around to see how this should be done, however I have yet to find an answer so I thought I would open an issue and see if anyone can advise. In the meantime, I'll keep digging 😄

**Comment by district18nb** [comment]
I believe I have resolved this issue.

As the story goes, it is a best practice to register the taxonomies *before* the post types. Seems to be, if a taxonomy is registered *after* a post, weird stuff happens.

It's a quick fix. In `Poet.php` we just move `TaxonomyModule::class` above `PostTypeModule::class` so the taxonomy module is loaded first.

https://github.com/Log1x/poet/blob/e01715f89351e03eae53f3cadb548e0242183b9c/src/Poet.php#L41-L48

Then, to properly configure the taxonomy, we set the `public` value to `true`.

```
'taxonomy' => [
    'genres' => ['book'],
    ...
    'public' => true,
]
```

Log1x, I appreciate your time developing this plugin, so I'd be happy to do a pull request (full disclosure: I've never done a PR, but I can try) to fix this and add some documentation (such as indicating how to create templates for the taxonomies and properly configure the taxonomy).
