### ISSUE TITLE
Action hook localizing a cpt

### ISSUE THREAD

**Issue by SergiArias** [Log1x/poet#27]
Trying to localize the cpt, I was able to do it by using the following action:
```php
add_action('after_setup_theme', function () {
    load_theme_textdomain('sage', get_template_directory() . '/resources/lang');
}, 4);
```

The problem is that if I use 5 and more in the priority, it doesn't get localized and I don't understand why, as it doesn't happen when using the extended-cpt on my own.
I was digging in the code to see in which action hook the cpt is registered, but I didn't understand the process with acorn.
So, how should we hook the textdomain? I think the answer should be present in the docs.

Thanks!

**Comment by Log1x** [comment]
Can you try removing the priority as seen on #25 and see if it fixes it?

**Comment by SergiArias** [comment]
I tried without priority, with priority 20, and a lot of others, and it only works with 4,3,2,1,0. No priority or 5 and above doesn't work :(

**Comment by Log1x** [comment]
try `composer require log1x/acf-composer:dev-master` and let me know if the latest change works

**Comment by SergiArias** [comment]
Tried it, but unfortunately, the behaviour is the same.

**Comment by Log1x** [comment]
I suspect this has to do with when Acorn is actually initialized then :( not sure if I'll be able to fix it? would be a trial & error kinda thing to attempt a fix.

**Comment by SergiArias** [comment]
Don't worry, fortunately it works fine, although it's annoying to not knowing the why. But I suggest to update the docs with this particularity so the user don't have to figure it out.
