### ISSUE TITLE
Shouldn't add_filter be add_action?

### ISSUE THREAD

**Issue by huubl** [Log1x/poet#34]
https://github.com/Log1x/poet/blob/c38e17feb063925c771b680947413823eba7016b/src/Poet.php#L68

**Comment by Log1x** [comment]
https://core.trac.wordpress.org/browser/tags/5.8/src/wp-includes/plugin.php#L394

**Comment by huubl** [comment]
Ah thanks

**Comment by Log1x** [comment]
sorry didn't mean to `close with comment` originally.

generally I just use `add_filter` since most of the action functions are just aliases for filtering.

**Comment by huubl** [comment]
No problem. Didn't know that most of the `add_action` functions are mostly aliases, learned something today!
