### ISSUE TITLE
$content is empty when the only content is an img

### ISSUE THREAD

**Issue by brinkofblink** [Log1x/poet#43]
Hi there,

First off, thanks for creating this module, it's hugely helpful in getting up and running with custom blocks in Sage! 

I've written a custom carousel block which allows a custom carousel-slide block as its inner blocks. Each carousel-slide block can accepts a single core/image block.

The blade template shows `$content` as empty unless the image has a caption.

I had a quick look at `poet/src/Modules/BlockModule.php` - it seems `isEmpty()` returns `true` when an image alone is used.
The block markup saved in the db is as follows (with the attributes removed for easier reading): 

```
<!-- wp:sage/carousel -->
<div class="wp-block-sage-carousel"><!-- wp:sage/carousel-slide -->
  <div><!-- wp:image -->
  <figure class="wp-block-image size-large"><img src="/app/uploads/2022/08/Image-Filename.jpeg" alt="" class="wp-image-259"/></figure>
  <!-- /wp:image --></div>
  <!-- /wp:sage/carousel-slide -->
  
  <!-- wp:sage/carousel-slide -->
  <div><!-- wp:image -->
  <figure class="wp-block-image size-large"><img src="/app/uploads/2022/08/Another-Image-Filename.jpg" alt="" class="wp-image-262"/></figure>
  <!-- /wp:image --></div>
  <!-- /wp:sage/carousel-slide --></div>
<!-- /wp:sage/carousel -->

```
Is there something different I need to do here?
I'm pretty new to Sage 10, Laravel, and block development so please excuse me if I'm missing something entirely!

**Comment by Log1x** [comment]
It's been awhile since I've played with Poet's block module but I think you can set `strip` to false in `poet.php` e.g.

```php
'sage/accordion' => ['strip' => false]
````

**Comment by brinkofblink** [comment]
Ah that's perfect, thanks! I missed that in the docs.
