### ISSUE TITLE
Registered block not available in block library

### ISSUE THREAD

**Issue by unscripted** [Log1x/poet#45]
## Problem

When registering a block in `config/poet.php` it is not available in the block library.

> Note: Registered post types, taxonomies, block patterns and block pattern categories work as expected.

## Expected result

Based on the [Registering a Block](https://github.com/Log1x/poet#registering-a-block) docs, I expect that uncommenting the default block example should result in an “Accordion” block being available in the block library.

I’m sure I’m missing an obvious step but if not, I wanted to provide my steps to reproduce.

### Environment

- Wordpress >= 6.0.3
- Sage = 10.3.1
- Poet = 2.0.7
- Node >= 16
- Composer = 2
- PHP >= 7.4

### Setup

1. Create a clean WordPress install
2. Install Sage 10.3.1
3. Install Poet
4. Uncomment the block example in the `config/poet.php` file
5. Add a new post and attempt to add the new accordion block

> Note: I have also tested adding a `accordion.blade.php` file to `resources/views/blocks/` and `views/blocks/` directories.

**Comment by Log1x** [comment]
Hmm. I don't use this feature so I didn't know anything was wrong with it.

I'm not exactly sure though. I tried using `register_block_type()` outside of Poet and still can't seem to get a block to register in the editor. 

I'm seeing:

```php
^ WP_Block_Type {#2372 ▼
  +api_version: 1
  +name: "app/example"
  +title: ""
  +category: null
  +parent: null
  +ancestor: null
  +icon: null
  +description: ""
  +keywords: []
  +textdomain: null
  +styles: []
  +variations: []
  +supports: null
  +example: null
  +render_callback: Closure() {#2369}
  +attributes: array:1 [▶]
  +uses_context: []
  +provides_context: null
  +editor_script_handles: []
  +script_handles: []
  +view_script_handles: []
  +editor_style_handles: []
  +style_handles: []
  -deprecated_properties: array:5 [▶]
}
```

being returned when registering. I figured maybe it needed a `title`, `category`, etc. set on it, but even when I do that, I'm getting nothing.

I checked `wp.blocks.getBlockTypes();` in console and it is not showing up there, either.

I'll have to tinker more but not sure if the usage of this function was updated in core at some point or if I'm going crazy. :)

**Comment by unscripted** [comment]
Thanks for taking a look. I thought I was going crazy too. haha

You mentioned not using this feature. How are you adding custom blocks to Sage that aren't ACF based?

**Comment by Log1x** [comment]
> You mentioned not using this feature. How are you adding custom blocks to Sage that aren't ACF based?

I only use ACF for blocks. I've [written a few](https://twitter.com/Log1x/status/1200040402679664640) native blocks in the past – they are great, but once ACF got InnerBlock support, I was sold as I'm much more comfortable with PHP in the end.

When I was using native blocks I used the same approach as Poet though:

```php
add_action('init', function () {
    return collect([
        'block/product',
    ])->each(function ($block) {
        register_block_type($block, [
            'render_callback' => function ($data, $content) use ($block) {
                return view(resource_path('views/blocks/' . Str::after($block, '/') . '.blade.php'), [
                    'data' => (object) $data,
                    'content' => ! empty(wp_strip_all_tags($content, true)) ? $content : null
                ]);
            }
        ]);
    });
}, 20);
```

so I'm definitely confused on what could be wrong.

**Comment by braco** [comment]
think I'm having this problem too. Is this feature broken in poet?

**Comment by Log1x** [comment]
Have you registered your block in the editor after registering the block with Poet?

```js
import { __ } from '@wordpress/i18n';
import { registerBlockType } from '@wordpress/blocks';
import { InnerBlocks } from '@wordpress/block-editor';

import { edit } from './edit';

registerBlockType('block/example', {
  title: __('Example', 'app'),
  description: 'An example block.',
  category: 'common',
  icon: 'star-filled',
  attributes: {
    title: {
      type: 'string'
    },
  },
  edit,
  save: props => <InnerBlocks.Content />
});
```
