### ISSUE TITLE
Manually publish 

### ISSUE THREAD

**Issue by rguttersohn** [Log1x/poet#48]
Not an issue. More of a question.

For the life of me I cannot get WP CLI to work with m Roots/Trellis/Sage 10x.  Therefore I cannot, I get the below command to work.

```
$ wp acorn vendor:publish --provider="Log1x\Poet\PoetServiceProvider"
```

How would this command be pulled off manually? Could I simply copy and past the class into the Provider folder? Also in what config file would I add the poet.php file? The only config directory I see is in the Bedrock portion of the stack.

**Comment by Log1x** [comment]
What errors are you getting with WP CLI? What's not working about it? You'll want CLI so you can initialize Acorn and have it create it's config folder (will typically get created in the theme).

**Comment by rguttersohn** [comment]
I actually didn't know the commands had to be run in the VM. Once I ssh'd into it and navigated to current, the commands worked.
