### ISSUE TITLE
Query vars not working aside post_types archives pages

### ISSUE THREAD

**Issue by PettersonGo** [Log1x/poet#49]
Hi guys, whats up?

I have a problem and i'll try to explain the best I can.

I have a post called article, i have created an archive for this post_type, its called on the route: 'https://siteurl.com/previous-editions'

This url lists the articles paginated by terms, so for example, i have an taxonomy with the slug 'edition', and this tax has its terms, all the terms have only posts with the post_type 'article'. Each page has 9 terms.

My main problem is in a functionality that I'm creating that the user searches for a specific term using the term slug(ex: edition-1). The way i thought to make this works was to add an form with one input that gets the term slug and submit it as a query params. So the url will be like this: 'https://siteurl.com/previous-editions/?edition=1'  and now instead of the query return all 9 terms related to the page it will only bring 1 term with the given slug, in this case, the term with edition-1.

But after the form submits, it throws an error and says that the page was not found, but it shouldn't happen because its the same page and the same url with only the query params as an extra.

So in the poet post configuration is there a way to allow using query params without throwing this error???

```php
return [
    'post' => [
        'article' => [
              'enter_title_here' => 'Insert the article title',
              'can_export'          => true,
              'capability_type'     => 'post',
              'exclude_from_search' => false,
              'has_archive'         => 'previous-editions',
              'hierarchical'        => false,
              'menu_icon'           => 'dashicons-book',
              'public'              => true,
              'publicly_queryable'  => true,
              'query_var'           => true,
              'rewrite'             => [
                                          'slug'       => 'magazine/%edition%',
                                          'with_front' => true,
                                          'pages'      => true,
                                          'feeds'      => true,
                                       ],
              'show_in_menu'        => true,
              'show_in_nav_menus'   => false,
              'show_ui'             => true,
              'taxonomies'          => ['post_tag'],
              'supports'            => ['title', 'editor', 'author', 'thumbnail', 'excerpt', 'comments', 'revisions'],
           ],
  ],
]
```

**Comment by Log1x** [comment]
Where/how are you defining the query vars?

Have you checked out https://github.com/johnbillion/extended-cpts/wiki/Query-vars-for-filtering ?
