### ISSUE TITLE
Register fields with WP GraphQL

### ISSUE THREAD

**Issue by troyblakelydc** [Log1x/poet#51]
I am trying to register custom fields to the wp-graphql plugin with ACF. Per [the documentation](https://github.com/wp-graphql/wp-graphql-acf#registering-fields-in-php), fields can be registered in PHP by adding:
`'show_in_graphql' => true,  'graphql_field_name' => 'myGroup',`

I added these attributes to the `admin_cols` collection of the custom post type, and it doesn't seem to be recognized by wp-graphql. I'm not sure if this is an issue with poet, extended-cpts or wp-graphql, but any suggestions would be appreciated.

**Comment by Log1x** [comment]
What are you expecting when adding them to `admin_cols`? For a true/false value to show up in the Post list screen?

In any case, I don't think this is related to Poet.

**Comment by troyblakelydc** [comment]
We have a custom post type called "release" that we have flagged to 'show_in_graphql' as shown below. This successfully adds the custom post type to the GQL schema. Everything works there. 

'post' => [
        'release' => [
            'supports' => ['title', 'thumbnail'],
            'show_in_rest' => true,
            'labels' => [
                'singular' => 'Release',
                'plural' => 'Releases',
            ],
            'admin_cols' => [...]
            ],
            'show_in_graphql' => true,
            'graphql_single_name' => 'release',
            'graphql_plural_name' => 'releases',
        ],


However, each custom field that you want exposed to the GQL schema also needs to be explicitly added. [The documentation](https://github.com/wp-graphql/wp-graphql-acf#registering-fields-in-php) shows this being done as the field group is added to ACF. I'm not sure if/how this might map into poet. I tried adding it into the admin_cols section both as an attribute of admin_cols, and as attributes of a give field and neither one worked. My goal is to see the custom fields (in this example case "artist") in the GQL schema, so I could query them like so:

`query GetPosts {
  releases {
    nodes {
      artist
    }
  }
}`

'admin_cols' => [
                'artist' => ['post_field' => 'artist', 
                'meta_key' => 'artist',
                'show_in_graphql' => true,
                'graphql_field_name' => 'artist_group',],
                ...
                ],
                'show_in_graphql' => true,
                'graphql_field_name' => 'admin_cols',
            ],

**Comment by Log1x** [comment]
Sorry for the late reply.

This wouldn't be related to Poet. `admin_cols` simply lets you add more columns to the list of posts in the backend.

You need to add `show_in_graphql` to your field group its self when registering it.

If you're using [ACF Composer](https://github.com/log1x/acf-composer), you can do it when you initialize FieldsBuilder like this:

```php
$example = new FieldsBuilder('example', [
    'show_in_graphql' => true, 
    'graphql_field_name' => 'My field name',
]);
```

**Comment by troyblakelydc** [comment]
We ended up calling `register_graphql_fields` and `acf_add_local_field_group` and `register_post_type` in setup.php. Less concise, but it worked!
