### ISSUE TITLE
Error including functions in config file

### ISSUE THREAD

**Issue by Alex-Hay** [Log1x/poet#54]
I'm using Poet to register a custom post type, and assign a few columns to it. Based on the Poet and Extended CPT, i've put together the code below. It works, but does display an error when I run `wp acorn optimize`: `Your configuration files are not serializable` and `Call to undefined method Closure::__set_state()`.

I’ve tried using a value function: `value(function() { echo 'example thing to echo'; })` which stops the error but doesn’t display in the column and i’ve also tried including the function outside of the object, which again stopped the error but doesn’t display anything.

Do you have suggestions of how columns can be added with Poet without causing this error? Thanks! 🙂

```
...
'post' => [
        'our-work' => [
            'enter_title_here' => 'Enter Project Name',
            'menu_icon' => 'dashicons-media-document',
            'supports' => ['title', 'editor', 'revisions', 'excerpt', 'thumbnail'],
            'show_in_rest' => true,
            'has_archive' => false,
            'menu_position' => 7,
            'public' => true,
            'show_in_rest' => true,
            'labels' => [
                'singular' => 'Post',
                'plural' => 'Work',
            ],
            'rewrite' => [
                'slug' => 'our-work',
                'with_front' => false
            ],
            'admin_cols' => [
                'tagline' => [
                    'title'    => 'Tagline',
                    'function' => function () {
                        echo 'test';
                    },
                ],
                'featured_image' => [
                    'title'          => 'Feature Image',
                    'featured_image' => 'medium',
                    'height'         => 40,
                ],
                'post_excerpt' => [
                    'title'    => 'Excerpt',
                    'function' => function () {
                        echo 'test';
                    },
                ]
            ],
        ],
    ],
...
```

**Comment by Log1x** [comment]
This is a limitation with Laravel's configuration. Serializing closures like that is generally very hacky.

I'm not sure how the callback functionality works internally for the `admin_cols` stuff on Extended CPT, but ideally you'd pass this functionality as callables instead.

So something like:
```php
...
'tagline' => [
    ...
    'function' => [OurWorkAdminColumns::class, 'tagline'],
]
```
where you have an `OurWorkAdminColumns` class that has a method called `tagline` which contains your `echo 'test';`.

Although, I'm not sure if this will work. Poet might have to do something to make this work as intended.

**Comment by Alex-Hay** [comment]
Hey @Log1x, thanks for your response! 

Looking into it a bit more, a resolution turned out to be surprisingly simple. I was able to create a function in the global namespace and call it in the config with no issues.

In case it's helpful for anyone, here's an example of displaying a custom field:

### poet.php
```
...
'admin_cols' => [
    'tagline' => [
        'title'    => 'Tagline',
        'function' => 'columnsDisplayTagline',
    ],
],
...
```

### helpers.php
I registered helpers in functions.php alongside setup and filters
```
function columnsDisplayTagline()
{
    echo get_field('tagline');
}
```
