### ISSUE TITLE
Can not register post type again when move code to server or pull code to another devices

### ISSUE THREAD

**Issue by techvsi-huynguyen** [Log1x/poet#57]
I can register cpt by run 

- `wp acorn cache:clear`
- `wp acorn vendor:publish --provider="Log1x\Poet\PoetServiceProvider`

But when I deploy code to server or another one pull code  and re-run the cmd above. The CPT doesn't register and show on admin side.

**Comment by Log1x** [comment]
You shouldn't need to repeatedly clear the cache nor re-publish the Poet config if you had already published it previously.

Have you added the `post-autoload-dump` to your `composer.json` as shown in the [Acorn install docs](https://roots.io/acorn/docs/installation/)?

**Comment by techvsi-huynguyen** [comment]
Yes I did. But it still not showing

**Comment by Log1x** [comment]
Unfortunately you will have to debug a bit to see why that might be the case. There's no way for me to really know why it wouldn't be registering. Does `wp acorn vendor:publish` still show Poet as an option on the server? I can confidently say this isn't an issue with Poet it's self, so something weird is happening.

**Comment by techvsi-huynguyen** [comment]
I checked the poet isn't in the vendor:publish. What should I do ? 
![Screenshot 2024-03-06 at 10 11 25](https://github.com/Log1x/poet/assets/113961209/f6a76472-b293-4522-9e39-76de0eb79088)

**Comment by Log1x** [comment]
Is Poet installed in the same `composer.json` as Acorn/ACF Composer?

**Comment by techvsi-huynguyen** [comment]
![Screenshot 2024-03-06 at 10 15 06](https://github.com/Log1x/poet/assets/113961209/5faddb10-9fd2-462c-8191-a5525611af91)
I checked that composer.json have poet. Yes I install ACF Composer too

**Comment by Log1x** [comment]
Sorry for a lack of reply on this but I hope you figured it out. I'm confident this isn't an issue directly related to Poet. 😦

**Comment by mattn-bbe** [comment]
Any luck @techvsi-huynguyen? I have the same issue - all is working on my local, but I can't see the CPT on server admin (I see all necessary files though)

**Comment by techvsi-huynguyen** [comment]
@mattn-bbe yeah, I ran` wp acorn vendor:clear` to solve this issue
