### ISSUE TITLE
Callback for custom fields in CPT

### ISSUE THREAD

**Issue by nexus23** [Log1x/poet#58]
Hey ... is there a way to add a callback in Poet to define custom fields for a custom post type (CPT);
AND if possible, could you give me an example/guide on how to integrate the callback?
That would be wonderful.
Thank you very much!

... I see that it could apparently be quite feasible ...
public $register_meta_box_cb
/vendor/johnbillion/args/src/register_post_type.php

**Comment by lajennylove** [comment]
Hey @nexus23 have you tried @Log1x 's ACF composer?

https://github.com/Log1x/acf-composer

I found it quite easy to integrate CF into my CPTs, it is not by a callback but it works well anyway.

**Comment by nexus23** [comment]
Hey @lajennylove ... thanks for the hint ... but i already figured it out ... thats what you have to put in poet.php fot a CPT called "contact_person"

`    /*
    |--------------------------------------------------------------------------
    | Post Types
    |--------------------------------------------------------------------------
    |
    | Here you may specify the post types to be registered by Poet using the
    | Extended CPTs library. <https://github.com/johnbillion/extended-cpts>
    | wordpress/app/themes/etracker/vendor/johnbillion/args/src/register_post_type.php
    */

    'post' => [
        'contact_person' => [
            'enter_title_here' => 'Enter new person for contact',
            'menu_icon' => 'dashicons-id',
            'supports' => ['title', 'thumbnail', 'custom-fields', 'revisions', 'page-attributes'],
            'capability_type' => 'page',
            'show_in_rest' => true,
            'show_in_feed' => false,
            'has_archive' => false,
            'delete_with_user' => false,
            'labels' => [
                'singular' => 'Contact',
                'plural' => 'Contacts',
                'slug' => 'contact-person'
            ],
            'admin_cols' => [
                'contact_role' => [
                    'taxonomy' => 'contact_role',
                ]
                'date'
            ]
        ]
       ]`
